### ISSUE TITLE
Recognize URL schemes to propose opening pads directly into Padland

### ISSUE THREAD

**Issue by Porkepix** [mikifus/padland#49]
It would be really nice to be able to directly open pads URLs, like clicking one anywhere in Android and besides allowing to open it in the browser, also offer to open it into padland.

I'm not sure this is possible as there isn't really a defined URI like `git://` and so on so it would require to use either the whole list of known instances, or some keywords in URLs (risk of false positives I guess).

**Comment by Porkepix** [comment]
I was going to open another issue but it would actually be very close to this one.

Currently you have to manually register a pad, which is the same way as for creating one and unpleasant way to do it if the URL is pseudo-random or completely random. User should be able to open an existing pad as a "one-shot" open, ie. without registering this pad into the application.

In the worst case by pasting the URL somewhere in the application.

**Comment by mikifus** [comment]
As Etherpad is a web service, URIs in the form of ```https://``` are to be parsed. But in order to not conflict with regular URLs I implemented it in such a way that you can "share" the URL to the app and it will work (as far as the server is in your whitelist).

It's not complicated to accept ```etherpad://``` as a URI, but I am not sure this would be correct or even useful, as it is the same as using the http schema and only this app will be able to manage it.

Any information or research on how the user experience can be improved is welcome.

**Comment by NA0341** [comment]
You can add all default pads to the list of supported URL's and add an option in settings to add custom server entries as well (on demand) (if this is technically possible).

![Screenshot_20211008-025227_Settings_Padland_v 1 8](https://user-images.githubusercontent.com/26059513/136481637-eeca7319-e0c2-4bf2-8b9d-3d5e1940a55b.jpg)

**Comment by mikifus** [comment]
Fixed by #71
