### ISSUE TITLE
systemli.org is redirected to pad.picasoft.net – wrong server url

### ISSUE THREAD

**Issue by dw-loewe** [mikifus/padland#72]
"pad.systemli.org" should be in the hard coded server list instead of "systemli.org". :-)
Now, it's redirected as said – why ever. Actual workaround: Adding pad.systemli.org to custom server list.

**Comment by mikifus** [comment]
While the name in the list is indeed _systemli.org_, the whitelist server is set up to _pad.systemli.org_ and the prefixed url is _https://pad.systemli.org/p/_.

You can see the configuration here:
https://github.com/mikifus/padland/blob/master/app/src/main/res/values/etherpad_servers.xml

What's exactly the issue you are having?

**Comment by y3n4** [comment]
Hey. I can reproduce the problem, but it seems to me that to issues got conflated here :) I think the mapping of the selected Server name and the server URLs in the creation of a new pad is somehow broken: When I chose "Caminho das Aguas" as a Host, the pad gets created at pad.systemli.org, if I choose systemli as a Host, it gets created pad.picasoft.net and so on. So imho it is not a redirection issue, but rather looks to me like the mapping is somehow shifted, but I don't know where in the code it is happening so that is just a guess.
